name: "vnetconn-corp1-${environment}"
virtual_network_name: "corp-vnet1-${environment}"
vhub_name: "hub1-${environment}"
enable_internet_security: true
routing_configuration:
  associated_route_table: null
  propagated_route_tables:
    - "default"