name: "vnetconn-corp4-${environment}"
virtual_network_name: "corp-vnet4-${environment}"
vhub_name: "hub4-${environment}"
enable_internet_security: true
routing_configuration:
  associated_route_table: null
  propagated_route_tables:
    - "default"