# Virtual WAN Infrastructure Configuration - Production Environment
# This file controls what gets deployed and updated in the Virtual WAN environment

environment: prod
region: eastus

# Virtual WAN Core Configuration
vwan_core:
  enabled: true
  name: "vwan-prod"
  resource_group: "rg-vwan-prod"
  type: "Standard"
  location: "eastus"
  
  # Firewall Configuration
  firewall:
    enabled: true
    name: "fw-prod"
    policy_name: "fw-policy-prod"
    sku: "Standard"
    public_ip_name: "pip-fw-prod"
    vnet_name: "vnet-fw-prod"
    vnet_address_space: "10.0.0.0/16"
    firewall_subnet: "10.0.1.0/26"
    management_subnet: "10.0.2.0/26"

# Hub Configurations
hubs:
  hub1:
    enabled: true
    name: "hub1-prod"
    address_prefix: "192.168.0.0/16"
    sku: "Standard"
    hub_routing_preference: "ASPath"
    location: "eastus"
    
    # VPN Gateway Configuration
    vpn_gateway:
      enabled: true
      name: "vpngw1-prod"
      scale_unit: 1
    
    # ExpressRoute Gateway Configuration
    express_route_gateway:
      enabled: true
      name: "ergw1-prod"
      scale_unit: 1

  hub2:
    enabled: true
    name: "hub2-prod"
    address_prefix: "192.168.1.0/16"
    sku: "Standard"
    hub_routing_preference: "ASPath"
    location: "eastus"
    
    vpn_gateway:
      enabled: false
    
    express_route_gateway:
      enabled: true
      name: "ergw2-prod"
      scale_unit: 1

  hub3:
    enabled: false
    name: "hub3-prod"
    address_prefix: "192.168.2.0/16"
    sku: "Standard"
    hub_routing_preference: "ASPath"
    location: "eastus"
    
    vpn_gateway:
      enabled: false
    
    express_route_gateway:
      enabled: false

  hub4:
    enabled: false
    name: "hub4-prod"
    address_prefix: "192.168.3.0/16"
    sku: "Standard"
    hub_routing_preference: "ASPath"
    location: "eastus"
    
    vpn_gateway:
      enabled: false
    
    express_route_gateway:
      enabled: false

# Spoke VNets Configuration
spoke_vnets:
  app-vnet:
    enabled: true
    name: "vnet-app-prod"
    type: "application"
    address_space: "172.16.0.0/16"
    hub_connection: "hub1-prod"
    internet_security_enabled: true
    
    subnets:
      - name: "app-subnet"
        address_prefix: "172.16.1.0/24"
        delegation: null
      - name: "db-subnet"
        address_prefix: "172.16.2.0/24"
        delegation: null
    
    network_security_group:
      subnet_name: "app-subnet"
      rules:
        - name: "allow-https"
          priority: 100
          direction: "Inbound"
          access: "Allow"
          protocol: "Tcp"
          source_port_range: "*"
          destination_port_range: "443"
          source_address_prefix: "*"
          destination_address_prefix: "*"

  data-vnet:
    enabled: true
    name: "vnet-data-prod"
    type: "data"
    address_space: "172.17.0.0/16"
    hub_connection: "hub2-prod"
    internet_security_enabled: false
    
    subnets:
      - name: "data-subnet"
        address_prefix: "172.17.1.0/24"
        delegation: null
      - name: "backup-subnet"
        address_prefix: "172.17.2.0/24"
        delegation: null

# Deployment Settings
deployment:
  auto_approve: true
  parallel_deployment: false
  max_parallel_hubs: 2
  timeout_minutes: 30 