name: "hub1-${environment}"
address_prefix: "192.0.0.0/16"
sku: "Standard"
hub_routing_preference: "ASPath"
vpn_gateway:
  name: "vpngw1-${environment}"
  scale_unit: 1
express_route_gateway:
  name: "ergw1-${environment}"
  scale_unit: 1 
