# Virtual WAN Infrastructure Configuration - Staging Environment
# This file controls what gets deployed and updated in the Virtual WAN environment

environment: staging
region: eastus

# Virtual WAN Core Configuration
vwan_core:
  enabled: true
  name: "vwan-staging"
  resource_group: "rg-vwan-staging"
  type: "Standard"
  location: "eastus"
  
  # Firewall Configuration
  firewall:
    enabled: true
    name: "fw-staging"
    policy_name: "fw-policy-staging"
    sku: "Standard"
    public_ip_name: "pip-fw-staging"
    vnet_name: "vnet-fw-staging"
    vnet_address_space: "10.2.0.0/16"
    firewall_subnet: "10.2.1.0/26"
    management_subnet: "10.2.2.0/26"

# Hub Configurations
hubs:
  hub1:
    enabled: true
    name: "hub1-staging"
    address_prefix: "192.170.0.0/16"
    sku: "Standard"
    hub_routing_preference: "ASPath"
    location: "eastus"
    
    # VPN Gateway Configuration
    vpn_gateway:
      enabled: true
      name: "vpngw1-staging"
      scale_unit: 1
    
    # ExpressRoute Gateway Configuration
    express_route_gateway:
      enabled: true
      name: "ergw1-staging"
      scale_unit: 1

  hub2:
    enabled: true
    name: "hub2-staging"
    address_prefix: "192.170.1.0/16"
    sku: "Standard"
    hub_routing_preference: "ASPath"
    location: "eastus"
    
    vpn_gateway:
      enabled: false
    
    express_route_gateway:
      enabled: true
      name: "ergw2-staging"
      scale_unit: 1

  hub3:
    enabled: false
    name: "hub3-staging"
    address_prefix: "192.170.2.0/16"
    sku: "Standard"
    hub_routing_preference: "ASPath"
    location: "eastus"
    
    vpn_gateway:
      enabled: false
    
    express_route_gateway:
      enabled: false

  hub4:
    enabled: false
    name: "hub4-staging"
    address_prefix: "192.170.3.0/16"
    sku: "Standard"
    hub_routing_preference: "ASPath"
    location: "eastus"
    
    vpn_gateway:
      enabled: false
    
    express_route_gateway:
      enabled: false

# Spoke VNets Configuration
spoke_vnets:
  staging-vnet:
    enabled: true
    name: "vnet-staging"
    type: "staging"
    address_space: "172.16.0.0/16"
    hub_connection: "hub1-staging"
    internet_security_enabled: true
    
    subnets:
      - name: "staging-subnet"
        address_prefix: "172.16.1.0/24"
        delegation: null

# Deployment Settings
deployment:
  auto_approve: true
  parallel_deployment: false
  max_parallel_hubs: 2
  timeout_minutes: 30 