name: 'Subscription Dispatch'

on:
  workflow_dispatch:
    inputs:
      yaml-String:
        description: 'YAML config string for one or more VNETs'
        required: true

jobs:
  create-team-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch is vnet_dev
        run: |
          echo "Branch is ${{ github.ref_name }}"
          if [ "${{ github.ref_name }}" != "vnet_dev" ]; then
            echo "This workflow only runs on the vnet_dev branch. Exiting."
            exit 1
          fi

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check if team folder exists
        run: |
          folder="teams/${{ fromJSON(github.event.inputs.yaml-String).teamname }}"
          echo "Checking if folder '$folder' exists..."
          if [ -d "$folder" ]; then
            echo "Team folder $folder already exists! Exiting."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create folder and generate multiple YAML files
        run: |
          echo "${{ github.event.inputs.yaml-String }}" > input.yaml
          npm install js-yaml
          node -e "
            const fs = require('fs');
            const yaml = require('js-yaml');
            const input = fs.readFileSync('input.yaml', 'utf8');
            const data = yaml.load(input);

            const teamname = data.teamname;
            const configs = data.configs;

            const folder = \`teams/\${teamname}\`;
            fs.mkdirSync(folder, { recursive: true });

            configs.forEach(cfg => {
              const vnetYaml = {
                name: \`corp-vnet1-\${cfg.environment}\`,
                address_prefix: '10.4.0.0/16',
                subnets: [
                  {
                    name: 'default',
                    prefix: '10.4.0.0/24'
                  }
                ]
              };

              const vnetConnYaml = {
                name: \`vnetconn-corp1-\${cfg.environment}\`,
                virtual_network_name: \`corp-vnet1-\${cfg.environment}\`,
                vhub_name: \`hub1-\${cfg.environment}\`,
                enable_internet_security: true,
                routing_configuration: {
                  associated_route_table: null,
                  propagated_route_tables: ['default']
                }
              };

              fs.writeFileSync(
                \`\${folder}/vnet_\${cfg.name}.yaml\`,
                yaml.dump(vnetYaml),
                'utf8'
              );

              fs.writeFileSync(
                \`\${folder}/vnet_connection_\${cfg.name}.yaml\`,
                yaml.dump(vnetConnYaml),
                'utf8'
              );
            });

            console.log('Generated all YAML configs for team:', teamname);
          "

      - name: Commit and push generated files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add teams/
          git commit -m "Add generated vnet and vnet_connection configs for multiple apps"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
